apiVersion: apps/v1 
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    app: shipping
    project: roboshop
    tier: app
spec:
  replicas: {{ .Values.shipping.replicas }}
  selector:
    matchLabels:
      app: shipping
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        app: shipping
        project: roboshop
        tier: app
    spec:
      containers:
      - name: shipping
        image: "narupallearun/shipping:{{ .Values.shipping.imageVersion }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        envFrom:
        - configMapRef:
            name: shipping        


      