apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:bootstrappers
        - system:nodes
      rolearn: arn:aws:iam::790021005618:role/eksctl-roboshop-project-nodegroup--NodeInstanceRole-epGRwqbFNHsn
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
        - roboshop-pod-reader
      userarn: arn:aws:iam::790021005618:user/ramesh-k8
      username: ramesh-k8
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 38c97e67-0701-4f19-96b7-8336289df2f2
