apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::790021005618:role/eksctl-roboshop-project-nodegroup--NodeInstanceRole-cNAwqpHbyVYC
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::790021005618:user/ramesh-k8
      username: ramesh-k8
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::790021005618:user/raheem-k8
      username: raheem-k8
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 9ed486ce-7c19-489e-9411-90217371bdb4