apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-pod-reader
rules: 
- apiGroups: [""] 
  resources: ["pods"]
  verbs:  ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop-pod-reader
  namespace: roboshop
subjects:
- kind: User
  name: ramesh-k8
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: roboshop-pod-reader
  apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   namespace: roboshop
#   name: cluster-reader-roboshop
# rules: 
# - apiGroups: [""] 
#   resources: ["secrets", "nodes", "persistantvolumes"]
#   verbs:  ["get", "watch", "list"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: cluster-reader-roboshop
#   namespace: roboshop
# subjects:
# - kind: User
#   name: ramesh-k8
#   apiGroup: rbac.authorization.k8s.io
# roleRef:
#   kind: ClusterRole
#   name: cluster-reader-roboshop
#   apiGroup: rbac.authorization.k8s.io
