apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-pod-reader
rules: 
- apiGroups: [""] 
  resources: ["pods"]
  verbs:  ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop-pod-reader
  namespace: roboshop
subjects:
- kind: user
  name: ramesh-k8
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: roboshop-pod-reader
  apiGroup: rbac.authorization.k8s.io


